<a href="https://colab.research.google.com/github/zh-mean/tensorflow-learn/blob/main/colab/tf_%E5%9F%BA%E7%A1%80%E6%93%8D%E4%BD%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'2.8.2'

In [3]:
x = [[1.]]
m = tf.matmul(x, x)
print(m)

tf.Tensor([[1.]], shape=(1, 1), dtype=float32)


In [4]:
x = tf.constant([[1,9], [3,6]])
x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 9],
       [3, 6]], dtype=int32)>